.gitignore, .prettierrc, server/app.js, server/models/Category.js, server/models/Group.js, server/models/GroupMember.js, server/models/GroupRequest.js, server/models/SocialLogin.js, server/models/Timer.js, server/models/User.js, server/models/index.js, server/package.json, server/routes/group_router.js, server/routes/index.js, server/routes/user_router.js
=> feat: 폴더 구조 설정

server/controller/ctrNotice.js, server/models/User.js, server/models/index.js, server/routes/index.js, server/routes/routerNotice.js
=> feat: notice CRUD

server/controller/ctrTodo.js, server/routes/index.js, server/routes/routerTodo.js
기존에 todo date도 클라이언트에서 넘겨줘야 했었는데 todo_index가 있으면 필요없을 것 같고 update_at에 DATE.now()로 수정해주면 될 것 같아서 이 부분 API문서에서 수정했습니다!
=> feat: todo CRUD 완성

server/controller/ctrTodo.js, server/models/Todo.js
todo 테이블에 done(완료여부) column을 추가하고 그에 따라 update도 수정 하였습니다
=> feat: todo done column추가 및 CRUD수정

server/controller/ctrGroup.js
- isSuccess:true/false boolean type으로 클라이언트 요청이 의도와 다르면 false 반환 통일 
- 서버 오류도 isSuccess:false 이나 code || status로 상태코드 반환
=> fix: ctrgroup 응답값 수정

server/controller/ctrUser.js
=> fix: 유저컨트롤러 kakaoAuth함수에서 db create email:값 변경

socketServer/package.json, socketServer/socket.js, socketServer/views/mongoose.html
=> refactor: mysql db 연결

server/controller/ctrNotice.js, server/controller/ctrTodo.js, server/controller/ctrUser.js, server/middlewares/isAdmin.js, server/routes/routerNotice.js, server/routes/routerTodo.js, server/routes/routerUser.js, server/utils/jwt.js
- Notice: 공지사항 API 토큰검사 미들웨어 적용 / 관리자 확인 미들웨어 적용
- Todo: Todo API 토큰검사 미들웨어 적용 / 토큰에서 user_id 값 가져오도록 일부 컨트롤러 코드 수정
=> refactor: 토큰 인증 미들웨어 적용

.gitignore, socketServer/controller/ctrChat.js, socketServer/schemas/Chat.js, socketServer/schemas/User.js, socketServer/schemas/index.js, socketServer/socket.js, socketServer/utils/io.js
- 귓속말 기능 아직 안입힌 상태
- 전 채팅 로그들 db에서 가져와서 뿌리기 (완료)
- 채팅 로그를 입력하면 db 에 저장 (완료)
=> Feature/chat 0.3v

server/controller/ctrUser.js
=> refactor: API서버- 유저정보수정 API 수정

server/controller/ctrNotice.js, server/routes/index.js, server/schemas/index.js, server/schemas/schema.js
sequelize구문으로 짜여있었던 notice controller를 mongoose로 리팩토링하였습니다.
=> refactor: notice CRUD sequelize->mongoose

server/controller/ctrNotice.js, server/controller/ctrTodo.js, server/routes/routerTodo.js, server/schemas/index.js, server/schemas/schema.js
-  todo CRUD를 sequeilze로 바꾸었습니다. 
- objId를 통해 서버에서 유저 정보를 가져와 더이상 params로 userId를 받아올 필요가 없어 라우트에서 제거하였습니다.
- status(500).json->status(500).send
=> refactor: todo CRUD sequelize->mongoose

server/controller/ctrGroupMongoose.js, server/routes/routerGroup.js, server/schemas/index.js, server/schemas/schema.js
group스키마에 password 삭제
user 스키마에 pending_groups 배열안에 is_approve 속성 삭제
group스키마에 join_requests 배열안에 is_approve 속성 삭제
=> fix: 데이터베이스 스키마 수정

server/controller/ctrNotice.js, server/controller/ctrTodo.js, server/routes/routerTodo.js, server/schemas/schema.js
- todo schema에서 done을 삭제하였습니다
- 이에 맞게 CRUD에서도 done과 관련된 작업을 삭제하였습니다.
- getTodoRouter에서 verifyJwtToken값을 넣어주었습니다.
=> fix: todo schema에서 done삭제 및 CRUD에서도 done관련 삭제, verifyJwtToken router 수정

server/controller/ctrNotice.js, server/controller/ctrTodo.js, server/schemas/schema.js
- DB 저장 그대로 UTC로
- 응답값 그대로 UTC로
- 프론트에서 한국시간으로 바꿈
=> refactor: API - Notice/Todo 시간 관련

server/controller/sns.js, server/package.json, server/routes/index.js
=> feat: 구글,네이버 로그인

server/controller/ctrAuth.js, server/controller/ctrUser.js, server/middlewares/jwt/jwt.js, server/routes/index.js, server/routes/routerAuth.js, server/routes/routerUser.js, server/utils/jwt.js
=> feat: 네이버 로그인 코드 수정 

server/controller/ctrAuth.js, server/controller/ctrUser.js, server/middlewares/jwt/jwt.js, server/routes/index.js, server/routes/routerAuth.js, server/utils/jwt.js
- 로그인시 리프레시토큰도 전달
- 리프레시 토큰으로 액세스토큰을 재발급 받는 API 추가
- 리프레시 토큰발급/검사 코드 추가
=> feat: 리프레시 토큰

server/controller/ctrCategoryRank.js, server/routes/index.js, server/routes/routerCategory.js, server/schemas/index.js
- postman으로 임의의 user의 ObjId 값을 통해 user의 Id값을 받아오는 것으로 바꿈
- 바로 서버에서 user의 정보를 받아오기 때문에 굳이 User 스키마를 뒤지지 않아도 됨!!! => 시간 단축!
=> feat:ranking postman test 완료 및 토큰값에서 유저 카테고리 받아오는 걸로 바꿈

server/controller/ctrGroup.js, socketServer/controller/ctrChat.js, socketServer/utils/io.js
- group스키마를 room 스키마로 동기화하지 않고 roomId를 groupId로 사용
=> fix: socket chat

server/schemas/schema.js, socketServer/schemas/schema.js, socketServer/utils/io.js
- sendMessage 소켓 이벤트에서 groupId를 하나 더 받아 오는 것으로 수정
- user 스키마 rooms필드 레퍼런스 수정
=> fix: save chat

socketServer/controller/ctrChat.js, socketServer/utils/io.js
joinRoom 이벤트 실행시 user의 socketId값인 token이 존재하는지 안하는지 컨트롤러 함수 실행 존재한다면, 채팅방에 계속 있었던 유저로 welcomeMessage만 클라이언트에 보내줌
존재하지 않는다면, 채팅방에 이전 채팅 로그들과 함께 welcomeMessage를 보내줌
=> fix: isToken 컨트롤러 함수 추가
